Use a newer setuptools for setuptools-scm
It turns out that setuptools-scm will complain if setuptools is not
new enough:

    $ python -m setuptools_scm
    /path/to/pce/venv/lib/python3.9/site-packages/setuptools_scm/integration.py:25: RuntimeWarning:
    ERROR: setuptools==44.1.1 is used in combination with setuptools_scm>=6.x

    Your build configuration is incomplete and previously worked by accident!
    setuptools_scm requires setuptools>=45

    This happens as setuptools is unable to replace itself when a activated build dependency
    requires a more recent setuptools version
    (it does not respect "setuptools>X" in setup_requires).

    setuptools>=31 is required for setup.cfg metadata support
    setuptools>=42 is required for pyproject.toml configuration support

    Suggested workarounds if applicable:
     - preinstalling build dependencies like setuptools_scm before running setup.py
     - installing setuptools_scm using the system package manager to ensure consistency
     - migrating from the deprecated setup_requires mechanism to pep517/518
       and using a pyproject.toml to declare build dependencies
       which are reliably pre-installed before running the build tools

      warnings.warn(
    Warning: could not use pyproject.toml, using default configuration.
     Reason: /path/to/pce/pyproject.toml does not contain a tool.setuptools_scm section.
    0.1.dev115+g26f8dc2.d20220623