Remove alias that does not work
With the not-working test alias:

> $ python setup.py test
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>    or: setup.py --help [cmd1 cmd2 ...]
>    or: setup.py --help-commands
>    or: setup.py cmd --help
>
> error: invalid command 'pytest'

When the alias is removed:

> $ python setup.py test
> running test
> WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
> running egg_info
> writing pce.egg-info/PKG-INFO
> writing dependency_links to pce.egg-info/dependency_links.txt
> writing top-level names to pce.egg-info/top_level.txt
> reading manifest file 'pce.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no files found matching 'Benchmark/*.py'
> writing manifest file 'pce.egg-info/SOURCES.txt'
> running build_ext
> 0
> Benchmarking (unittest.loader._FailedTest) ... ERROR
> test_lb_solve (tests.LoadBalancing.test_te_solver.Test_TE_Solver) ... Connectivity:2
> Min edge cut:2
> tm:[(6, 22, 8822.639986692711, 51), (12, 24, 7691.642736603715, 69), (9, 24, 8231.286428814663, 66)]
>
>  #Nodes:25
>
>  #Links:48
> request:3
> links:96
> bound 1:75
> bound 2:171
> bound 3:174
> r=3:m=25:n=96
> out:(75, 288)
>
> [...]
>
> [{'1': [[1, 9], [9, 11]], '2': [[3, 1], [1, 12], [12, 0], [0, 18]], '3': [[2, 12], [12, 16], [16, 9], [9, 13]]}, 14195698.0]
> Self solution:
> [{'1': [[1, 9], [9, 11]], '2': [[3, 1], [1, 12], [12, 0], [0, 18]], '3': [[2, 12], [12, 16], [16, 9], [9, 13]]}, 14195698.0]
> ok
>
> ======================================================================
> ERROR: Benchmarking (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: Benchmarking
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
>     module = __import__(module_name)
>   File "/home/sajith/projects/atlanticwave-sdx/pce/sdx/pce/Utility/Benchmarking.py", line 6, in <module>
>     from LoadBalancing.MC_Solver import runMC_Solver
> ModuleNotFoundError: No module named 'LoadBalancing'
>
>
> ----------------------------------------------------------------------
> Ran 8 tests in 19.164s
>
> FAILED (errors=1)
> Test failed: <unittest.runner.TextTestResult run=8 errors=1 failures=0>
> error: Test failed: <unittest.runner.TextTestResult run=8 errors=1 failures=0>